# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d02aeb421f5915f84517cefdbdcf530cd2ab303a30cc52e9c1840ce5f6055be9187c018464db0c66819f2faff4e1e4a5931c524f9aa4ed6d2cd2da8f19a20593

test:
  secret_key_base: 805722e4d95d701ae02cafd20b8982e95a6ae818a26fe88e4de3f52d90250f3bda286fc18b73b2dd924e8bfd3327481bfe43e4851d6ea7ad35f29ba9837520e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
